media: assets/pdf
content:
  - name: html-files
    label: HTML Pages
    folder: .
    extensions: ["html"]
    fields:
      - name: body
        label: Page Content
        type: string
        widget: text