media: assets/pdf
content:
  - name: pages
    label: Website Pages
    folder: .
    extensions: [html]
    fields:
      - name: title
        label: Page Title
        type: string
      - name: body
        label: Content
        type: rich-text
        