backend:
  name: github
  repo: hotak1/hotak1.github.io
  branch: main

media_folder: "assets/img" 
public_folder: "/assets/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "business/financial-services.html"
        label: "Financial Services Page"
        name: "financial_services"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Main Content", name: "body", widget: "markdown" }
